#
# Makefile for MStar Utopia2K STR device drivers.
#

# general options
ccflags-$(CONFIG_MSTAR_UTOPIA2K_STR)      +=  -Idrivers/mstar2/include
ccflags-$(CONFIG_MSTAR_UTOPIA2K_STR)      +=  -Idrivers/mstar2/drv/utopia2k_str
ccflags-$(CONFIG_MSTAR_UTOPIA2K_STR)      +=  -Idrivers/mstar2/include/sys/common
ccflags-$(CONFIG_MSTAR_UTOPIA2K_STR)      +=  -Idrivers/base/power
# specific options
ccflags-$(CONFIG_MSTAR_UTOPIA2K_STR)      +=

# files
obj-$(CONFIG_MSTAR_UTOPIA2K_STR)    += mdrv_utopia2k_str.o
mdrv-utopia2k-str-objs             += mdrv_utopia2k_str.o
