/**
* Copyright (c) 2006 - 2016 MStar Semiconductor, Inc.
* This program is free software. You can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
*/
//******************************************************************************
//
//
//
//
//
//
//
//
//
//******************************************************************************
#ifndef _UTIL_SYMBOL__HH__
#define _UTIL_SYMBOL__HH__
#if defined(MSOS_TYPE_NOS)
/*msAPI_Debug.c is used to exchange software symbols with MSTV_TOOL*/
typedef enum
{
    SYMBOL_MVD_VOL_INFO_BASE,
    SYMBOL_MVD_FRAME_INFO_BASE,
    SYMBOL_MVD_FRAME_AVAILABLE,
    SYMBOL_GOP_FB0_STARTADR,          //for GE use
    SYMBOL_GOP_FB0_WIDTH,
    SYMBOL_GOP_FB0_HEIGHT,
    SYMBOL_GOP_FB0_PITCH,
    SYMBOL_GOP_FB0_FORMAT,
    SYMBOL_GOP_FB0_STRING,
    SYMBOL_GOP_FB1_STARTADR,
    SYMBOL_GOP_FB1_WIDTH,
    SYMBOL_GOP_FB1_HEIGHT,
    SYMBOL_GOP_FB1_PITCH,
    SYMBOL_GOP_FB1_FORMAT,
    SYMBOL_GOP_FB1_STRING,
    SYMBOL_GOP_FB2_STARTADR,
    SYMBOL_GOP_FB2_WIDTH,
    SYMBOL_GOP_FB2_HEIGHT,
    SYMBOL_GOP_FB2_PITCH,
    SYMBOL_GOP_FB2_FORMAT,
    SYMBOL_GOP_FB2_STRING,
    SYMBOL_GOP_FB3_STARTADR,
    SYMBOL_GOP_FB3_WIDTH,
    SYMBOL_GOP_FB3_HEIGHT,
    SYMBOL_GOP_FB3_PITCH,
    SYMBOL_GOP_FB3_FORMAT,
    SYMBOL_GOP_FB3_STRING,
    SYMBOL_GOP_FB4_STARTADR,
    SYMBOL_GOP_FB4_WIDTH,
    SYMBOL_GOP_FB4_HEIGHT,
    SYMBOL_GOP_FB4_PITCH,
    SYMBOL_GOP_FB4_FORMAT,
    SYMBOL_GOP_FB4_STRING,
    SYMBOL_GOP_FB5_STARTADR,
    SYMBOL_GOP_FB5_WIDTH,
    SYMBOL_GOP_FB5_HEIGHT,
    SYMBOL_GOP_FB5_PITCH,
    SYMBOL_GOP_FB5_FORMAT,
    SYMBOL_GOP_FB5_STRING,
    SYMBOL_GOP_FB6_STARTADR,
    SYMBOL_GOP_FB6_WIDTH,
    SYMBOL_GOP_FB6_HEIGHT,
    SYMBOL_GOP_FB6_PITCH,
    SYMBOL_GOP_FB6_FORMAT,
    SYMBOL_GOP_FB6_STRING,
    SYMBOL_GOP_FB7_STARTADR,
    SYMBOL_GOP_FB7_WIDTH,
    SYMBOL_GOP_FB7_HEIGHT,
    SYMBOL_GOP_FB7_PITCH,
    SYMBOL_GOP_FB7_FORMAT,
    SYMBOL_GOP_FB7_STRING,
    SYMBOL_GOP_FB8_STARTADR,
    SYMBOL_GOP_FB8_WIDTH,
    SYMBOL_GOP_FB8_HEIGHT,
    SYMBOL_GOP_FB8_PITCH,
    SYMBOL_GOP_FB8_FORMAT,
    SYMBOL_GOP_FB8_STRING,
    SYMBOL_GOP_FB9_STARTADR,
    SYMBOL_GOP_FB9_WIDTH,
    SYMBOL_GOP_FB9_HEIGHT,
    SYMBOL_GOP_FB9_PITCH,
    SYMBOL_GOP_FB9_FORMAT,
    SYMBOL_GOP_FB9_STRING,
    SYMBOL_GOP_FB10_STARTADR,
    SYMBOL_GOP_FB10_WIDTH,
    SYMBOL_GOP_FB10_HEIGHT,
    SYMBOL_GOP_FB10_PITCH,
    SYMBOL_GOP_FB10_FORMAT,
    SYMBOL_GOP_FB10_STRING,
    SYMBOL_GOP_FB11_STARTADR,
    SYMBOL_GOP_FB11_WIDTH,
    SYMBOL_GOP_FB11_HEIGHT,
    SYMBOL_GOP_FB11_PITCH,
    SYMBOL_GOP_FB11_FORMAT,
    SYMBOL_GOP_FB11_STRING,
    SYMBOL_GOP_FB12_STARTADR,
    SYMBOL_GOP_FB12_WIDTH,
    SYMBOL_GOP_FB12_HEIGHT,
    SYMBOL_GOP_FB12_PITCH,
    SYMBOL_GOP_FB12_FORMAT,
    SYMBOL_GOP_FB12_STRING,
    SYMBOL_GOP_FB13_STARTADR,
    SYMBOL_GOP_FB13_WIDTH,
    SYMBOL_GOP_FB13_HEIGHT,
    SYMBOL_GOP_FB13_PITCH,
    SYMBOL_GOP_FB13_FORMAT,
    SYMBOL_GOP_FB13_STRING,
    SYMBOL_GOP_FB14_STARTADR,
    SYMBOL_GOP_FB14_WIDTH,
    SYMBOL_GOP_FB14_HEIGHT,
    SYMBOL_GOP_FB14_PITCH,
    SYMBOL_GOP_FB14_FORMAT,
    SYMBOL_GOP_FB14_STRING,
    SYMBOL_GOP_FB15_STARTADR,
    SYMBOL_GOP_FB15_WIDTH,
    SYMBOL_GOP_FB15_HEIGHT,
    SYMBOL_GOP_FB15_PITCH,
    SYMBOL_GOP_FB15_FORMAT,
    SYMBOL_GOP_FB15_STRING,
    SYMBOL_LAST
}DEBUG_SYMBOL;
void Util_InitSymbolTBL(void);
MS_BOOL Util_AddSymbol(DEBUG_SYMBOL symbol, MS_U32 value);
#endif

#endif
