EXTRA_CFLAGS                += -Idrivers/mstar2/include
EXTRA_CFLAGS                += -Idrivers/mstar2/drv/gpio/
EXTRA_CFLAGS                += -Idrivers/mstar2/hal/$(CONFIG_MSTAR_CHIP_NAME)/gpio/

# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o

