/**
* Copyright (c) 2006 – 2018 MStar Semiconductor, Inc.
* This program is free software. You can redistribute it and/or modify it under the terms of
* the GNU General Public License as published by the Free Software Foundation;
* either version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along with this program;
* if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
* MA 02111-1307, USA.
*/
//******************************************************************************
//******************************************************************************
#define MST_CODEC_NONE_PM1_ADDR     0x1380  
#define MST_CODEC_NONE_PM1_SIZE     0x0012  

BYTE code mst_codec_none_pm1[]=
{   //PM 1 Addr: 0x1380-0x217F[0x0E00] Len=0x0006(words)/18(bytes)
    0x01, 0x01, 0x80, 0x13, 0x12, 0x00,

    //start:0x001380, len:6(words), 18(bytes)
    0x00, 0x80, 0x07, 0x4A, 0x38, 0x41, 0x5A, 0xDD, 0x93, 0x0F, 0x00, 0x0A, 
    0x00, 0x00, 0x00, 0x0F, 0x00, 0x0A, 

};

#define MST_CODEC_NONE_PM3_ADDR     0xC000  
#define MST_CODEC_NONE_PM3_SIZE     0x0003  

BYTE code mst_codec_none_pm3[]=
{   //PM 3 Addr: 0xC000-0xCFFF[0x1000] Len=0x0001(words)/3(bytes)
    0x01, 0x01, 0x00, 0xC0, 0x03, 0x00,

    //start:0x00C000, len:1(words), 3(bytes)
    0x0F, 0x00, 0x0A, 

};

//Total: [PM1 0x0006/0E00 words] [PM2 0x0000/0001 words] [PM3 0x0001/1000 words] [PM4 0x0000/0F00 words] 
//Version:[FF.FF.FF](codec_none)
//Time: 2017/05/15 23:56:52
//Generated by MStar Audio DSP Pack Utility Ver. 4.46.00 <ellis.chen>
