/**
* Copyright (c) 2006 – 2018 MStar Semiconductor, Inc.
* This program is free software. You can redistribute it and/or modify it under the terms of
* the GNU General Public License as published by the Free Software Foundation;
* either version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along with this program;
* if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
* MA 02111-1307, USA.
*/
//******************************************************************************
//******************************************************************************
#define MST_CODEC_DEC_PM1_ADDR     0x2180  
#define MST_CODEC_DEC_PM1_SIZE     0x0012  

BYTE code mst_codec_dec_pm1[]=
{   //PM 1 Addr: 0x2180-0x21FF[0x0080] Len=0x0006(words)/18(bytes)
    0x01, 0x01, 0x80, 0x21, 0x12, 0x00,

    //start:0x002180, len:6(words), 18(bytes)
    0x00, 0x80, 0x07, 0x4A, 0x18, 0x42, 0x9A, 0xDD, 0x93, 0x0F, 0x00, 0x0A, 
    0x75, 0xDD, 0x33, 0x4F, 0x00, 0x0B, 

};

#define MST_CODEC_DEC_PM2_ADDR     0x4780  
#define MST_CODEC_DEC_PM2_SIZE     0x0021  

BYTE code mst_codec_dec_pm2[]=
{   //PM 2 Addr: 0x4780-0x4FFF[0x0880] Len=0x000B(words)/33(bytes)
    0x01, 0x01, 0x80, 0x47, 0x21, 0x00,

    //start:0x004780, len:1(words), 3(bytes)
    0x78, 0x88, 0x77, 

    //start:0x004781, len:10(words), 30(bytes)
    0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x02, 0x00, 0x00, 0x03, 0x00, 0x00, 
    0x04, 0x00, 0x00, 0x05, 0x00, 0x00, 0x06, 0x00, 0x00, 0x07, 0x00, 0x00, 
    0x08, 0x00, 0x00, 0x09, 0x00, 0x00, 

};

#define MST_CODEC_DEC_PM3_ADDR     0xD000  
#define MST_CODEC_DEC_PM3_SIZE     0x0003  

BYTE code mst_codec_dec_pm3[]=
{   //PM 3 Addr: 0xD000-0xEFFF[0x2000] Len=0x0001(words)/3(bytes)
    0x01, 0x01, 0x00, 0xD0, 0x03, 0x00,

    //start:0x00D000, len:1(words), 3(bytes)
    0x0F, 0x00, 0x0A, 

};

#define MST_CODEC_DEC_PM4_ADDR     0x12F00  
#define MST_CODEC_DEC_PM4_SIZE     0x0012  

BYTE code mst_codec_dec_pm4[]=
{   //PM 4 Addr: 0x12F00-0x12FFF[0x0100] Len=0x0006(words)/18(bytes)
    0x01, 0x01, 0x00, 0x2F, 0x12, 0x00,

    //start:0x012F00, len:6(words), 18(bytes)
    0xAA, 0xAA, 0xAA, 0xBB, 0xBB, 0xBB, 0xCC, 0xCC, 0xCC, 0xDD, 0xDD, 0xDD, 
    0xEE, 0xEE, 0xEE, 0xFF, 0xFF, 0xFF, 

};

//Total: [PM1 0x0006/0080 words] [PM2 0x000B/0880 words] [PM3 0x0001/2000 words] [PM4 0x0006/0100 words] 
//Version:[77.88.78](codec_dec)
//Time: 2017/05/15 23:48:39
//Generated by MStar Audio DSP Pack Utility Ver. 4.46.00 <ellis.chen>
