#
# Makefile for the Linux Bluetooth HCI device drivers.
#

ccflags-y       += -I$(srctree)/drivers/mstar2/drv/gpio
ccflags-y       += -I$(srctree)/drivers/mstar2/include
ccflags-y       += -I$(srctree)/arch/arm/include


obj-$(CONFIG_BRCM_BT)		+= brcm-bluetooth-rfkill.o


