EXTRA_CFLAGS    += -I$(srctree)/drivers/mstar2/drv/mmc/inc/api/
EXTRA_CFLAGS    += -I$(srctree)/drivers/mstar2/drv/mmc/inc/common/
EXTRA_CFLAGS    += -I$(srctree)/drivers/mstar2/drv/mmc/inc/config/
EXTRA_CFLAGS    += -I$(srctree)/drivers/mstar2/drv/mmc/hal/$(CONFIG_MSTAR_CHIP_NAME)/

obj-y += eMMC_platform.o
