/**
* Copyright (c) 2006 - 2016 MStar Semiconductor, Inc.
* This program is free software. You can redistribute it and/or modify it under the terms of
* the GNU General Public License as published by the Free Software Foundation;
* either version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along with this program;
* if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
* MA 02111-1307, USA.
*/

#ifndef _MSTAR_ADDR_INC_
#define _MSTAR_ADDR_INC_

MS_BUS_MIU1_0768M                       = 0xD0000000
MS_BUS_MIU1_0512M                       = 0xC0000000
MS_BUS_MIU1_0256M                       = 0xB0000000
MS_BUS_MIU1_0000M                       = 0xA0000000
MS_BUS_MIU0_1792M                       = 0x90000000
MS_BUS_MIU0_1536M                       = 0x80000000
MS_BUS_MIU0_1280M                       = 0x70000000
MS_BUS_MIU0_1024M                       = 0x60000000
MS_BUS_MIU0_0768M                       = 0x50000000
MS_BUS_MIU0_0512M                       = 0x40000000
MS_BUS_MIU0_0256M                       = 0x30000000
MS_BUS_MIU0_0000M                       = 0x20000000
MS_BUS_RIU_ADDR                         = 0x1F000000
MS_BUS_XIU_SPI_ADDR                     = 0x14000000
MS_BUS_BOOT_ADDR                        = 0x00000000

#endif
