/**
* Copyright (c) 2006 – 2018 MStar Semiconductor, Inc.
* This program is free software. You can redistribute it and/or modify it under the terms of
* the GNU General Public License as published by the Free Software Foundation;
* either version 2 of the License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
* without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
* See the GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License along with this program;
* if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
* MA 02111-1307, USA.
*/
////////////////////////////////////////////////////////////////////////////////
//****************************************************
//   Quality Map CodeGen Version 4.0
// Panel_1
// Maxim_TMO
// 2/16/2017  9:21:18 AM
// 42782.3897917
//****************************************************

#ifndef _MAXIM_TMO_TMO_H_
#define _MAXIM_TMO_TMO_H_

#define PQ_IP_NUM_TMO 2

typedef enum
{
    #if PQ_QM_VR
    QM_RESERVED0_TMO, //0
    #endif
    #if PQ_QM_VR
    QM_BT709_TMO, //1
    #endif
    #if PQ_QM_VR
    QM_UNSPECIFIED_TMO, //2
    #endif
    #if PQ_QM_VR
    QM_RESERVED3_TMO, //3
    #endif
    #if PQ_QM_VR
    QM_GAMMA2P2_TMO, //4
    #endif
    #if PQ_QM_VR
    QM_GAMMA2P8_TMO, //5
    #endif
    #if PQ_QM_VR
    QM_BT601525_601625_TMO, //6
    #endif
    #if PQ_QM_VR
    QM_SMPTE240M_TMO, //7
    #endif
    #if PQ_QM_VR
    QM_LINEAR_TMO, //8
    #endif
    #if PQ_QM_VR
    QM_LOG0_TMO, //9
    #endif
    #if PQ_QM_VR
    QM_LOG1_TMO, //10
    #endif
    #if PQ_QM_VR
    QM_XVYCC_TMO, //11
    #endif
    #if PQ_QM_VR
    QM_BT1361_TMO, //12
    #endif
    #if PQ_QM_VR
    QM_SRGB_SYCC_TMO, //13
    #endif
    #if PQ_QM_VR
    QM_BT2020NCL_TMO, //14
    #endif
    #if PQ_QM_VR
    QM_BT2020CL_TMO, //15
    #endif
    #if PQ_QM_VR
    QM_SMPTE2084_TMO, //16
    #endif
    #if PQ_QM_VR
    QM_SMPTE428_TMO, //17
    #endif
    #if PQ_QM_VR
    QM_ADOBERGB_TMO, //18
    #endif
    #if PQ_QM_VR
    QM_BT1886_TMO, //19
    #endif
    #if PQ_QM_VR
    QM_DOLBYMETA_TMO, //20
    #endif
    #if PQ_QM_VR
    QM_HLG_TMO, //21
    #endif
    QM_INPUTTYPE_NUM_TMO, // 22
} SC_QUALITY_MAP_INDEX_e_TMO;

typedef enum
{
PQ_IP_TMO_SOURCE_SETTING_TMO,  //0
PQ_IP_TMO_TARGET_SETTING_TMO,  //1
 }   PQ_IPTYPE_TMO;

typedef enum
{
PQ_IP_TMO_SOURCE_SETTING_COM_TMO,  //0
PQ_IP_TMO_TARGET_SETTING_COM_TMO,  //1
PQ_IP_COM_NUMS_TMO
} PQ_IP_COM_Group_TMO;

typedef enum
{
PQ_IP_TMO_SOURCE_SETTING_OFF_TMO,
PQ_IP_TMO_SOURCE_SETTING_RESERVED0_TMO,
PQ_IP_TMO_SOURCE_SETTING_BT709_TMO,
PQ_IP_TMO_SOURCE_SETTING_UNSPECIFIED_TMO,
PQ_IP_TMO_SOURCE_SETTING_RESERVED3_TMO,
PQ_IP_TMO_SOURCE_SETTING_GAMMA2P2_TMO,
PQ_IP_TMO_SOURCE_SETTING_GAMMA2P8_TMO,
PQ_IP_TMO_SOURCE_SETTING_BT601525_601625_TMO,
PQ_IP_TMO_SOURCE_SETTING_SMPTE240M_TMO,
PQ_IP_TMO_SOURCE_SETTING_LINEAR_TMO,
PQ_IP_TMO_SOURCE_SETTING_LOG0_TMO,
PQ_IP_TMO_SOURCE_SETTING_LOG1_TMO,
PQ_IP_TMO_SOURCE_SETTING_XVYCC_TMO,
PQ_IP_TMO_SOURCE_SETTING_BT1361_TMO,
PQ_IP_TMO_SOURCE_SETTING_SRGB_SYCC_TMO,
PQ_IP_TMO_SOURCE_SETTING_BT2020NCL_TMO,
PQ_IP_TMO_SOURCE_SETTING_BT2020CL_TMO,
PQ_IP_TMO_SOURCE_SETTING_SMPTE2084_TMO,
PQ_IP_TMO_SOURCE_SETTING_SMPTE428_TMO,
PQ_IP_TMO_SOURCE_SETTING_ADOBERGB_TMO,
PQ_IP_TMO_SOURCE_SETTING_BT1886_TMO,
PQ_IP_TMO_SOURCE_SETTING_DOLBYMETA_TMO,
PQ_IP_TMO_SOURCE_SETTING_HLG_TMO,
PQ_IP_TMO_SOURCE_SETTING_NUMS_TMO
} PQ_IP_TMO_SOURCE_SETTING_Group_TMO;

typedef enum
{
PQ_IP_TMO_TARGET_SETTING_OFF_TMO,
PQ_IP_TMO_TARGET_SETTING_RESERVED0_H_TMO,
PQ_IP_TMO_TARGET_SETTING_BT709_H_TMO,
PQ_IP_TMO_TARGET_SETTING_UNSPECIFIED_H_TMO,
PQ_IP_TMO_TARGET_SETTING_RESERVED3_H_TMO,
PQ_IP_TMO_TARGET_SETTING_GAMMA2P2_H_TMO,
PQ_IP_TMO_TARGET_SETTING_GAMMA2P8_H_TMO,
PQ_IP_TMO_TARGET_SETTING_BT601525_601625_H_TMO,
PQ_IP_TMO_TARGET_SETTING_SMPTE240M_H_TMO,
PQ_IP_TMO_TARGET_SETTING_LINEAR_H_TMO,
PQ_IP_TMO_TARGET_SETTING_LOG0_H_TMO,
PQ_IP_TMO_TARGET_SETTING_LOG1_H_TMO,
PQ_IP_TMO_TARGET_SETTING_XVYCC_H_TMO,
PQ_IP_TMO_TARGET_SETTING_BT1361_H_TMO,
PQ_IP_TMO_TARGET_SETTING_SRGB_SYCC_H_TMO,
PQ_IP_TMO_TARGET_SETTING_BT2020NCL_H_TMO,
PQ_IP_TMO_TARGET_SETTING_BT2020CL_H_TMO,
PQ_IP_TMO_TARGET_SETTING_SMPTE2084_H_TMO,
PQ_IP_TMO_TARGET_SETTING_SMPTE428_H_TMO,
PQ_IP_TMO_TARGET_SETTING_ADOBERGB_H_TMO,
PQ_IP_TMO_TARGET_SETTING_BT1886_H_TMO,
PQ_IP_TMO_TARGET_SETTING_DOLBYMETA_H_TMO,
PQ_IP_TMO_TARGET_SETTING_HLG_H_TMO,
PQ_IP_TMO_TARGET_SETTING_RESERVED0_M_TMO,
PQ_IP_TMO_TARGET_SETTING_BT709_M_TMO,
PQ_IP_TMO_TARGET_SETTING_UNSPECIFIED_M_TMO,
PQ_IP_TMO_TARGET_SETTING_RESERVED3_M_TMO,
PQ_IP_TMO_TARGET_SETTING_GAMMA2P2_M_TMO,
PQ_IP_TMO_TARGET_SETTING_GAMMA2P8_M_TMO,
PQ_IP_TMO_TARGET_SETTING_BT601525_601625_M_TMO,
PQ_IP_TMO_TARGET_SETTING_SMPTE240M_M_TMO,
PQ_IP_TMO_TARGET_SETTING_LINEAR_M_TMO,
PQ_IP_TMO_TARGET_SETTING_LOG0_M_TMO,
PQ_IP_TMO_TARGET_SETTING_LOG1_M_TMO,
PQ_IP_TMO_TARGET_SETTING_XVYCC_M_TMO,
PQ_IP_TMO_TARGET_SETTING_BT1361_M_TMO,
PQ_IP_TMO_TARGET_SETTING_SRGB_SYCC_M_TMO,
PQ_IP_TMO_TARGET_SETTING_BT2020NCL_M_TMO,
PQ_IP_TMO_TARGET_SETTING_BT2020CL_M_TMO,
PQ_IP_TMO_TARGET_SETTING_SMPTE2084_M_TMO,
PQ_IP_TMO_TARGET_SETTING_SMPTE428_M_TMO,
PQ_IP_TMO_TARGET_SETTING_ADOBERGB_M_TMO,
PQ_IP_TMO_TARGET_SETTING_BT1886_M_TMO,
PQ_IP_TMO_TARGET_SETTING_DOLBYMETA_M_TMO,
PQ_IP_TMO_TARGET_SETTING_HLG_M_TMO,
PQ_IP_TMO_TARGET_SETTING_RESERVED0_L_TMO,
PQ_IP_TMO_TARGET_SETTING_BT709_L_TMO,
PQ_IP_TMO_TARGET_SETTING_UNSPECIFIED_L_TMO,
PQ_IP_TMO_TARGET_SETTING_RESERVED3_L_TMO,
PQ_IP_TMO_TARGET_SETTING_GAMMA2P2_L_TMO,
PQ_IP_TMO_TARGET_SETTING_GAMMA2P8_L_TMO,
PQ_IP_TMO_TARGET_SETTING_BT601525_601625_L_TMO,
PQ_IP_TMO_TARGET_SETTING_SMPTE240M_L_TMO,
PQ_IP_TMO_TARGET_SETTING_LINEAR_L_TMO,
PQ_IP_TMO_TARGET_SETTING_LOG0_L_TMO,
PQ_IP_TMO_TARGET_SETTING_LOG1_L_TMO,
PQ_IP_TMO_TARGET_SETTING_XVYCC_L_TMO,
PQ_IP_TMO_TARGET_SETTING_BT1361_L_TMO,
PQ_IP_TMO_TARGET_SETTING_SRGB_SYCC_L_TMO,
PQ_IP_TMO_TARGET_SETTING_BT2020NCL_L_TMO,
PQ_IP_TMO_TARGET_SETTING_BT2020CL_L_TMO,
PQ_IP_TMO_TARGET_SETTING_SMPTE2084_L_TMO,
PQ_IP_TMO_TARGET_SETTING_SMPTE428_L_TMO,
PQ_IP_TMO_TARGET_SETTING_ADOBERGB_L_TMO,
PQ_IP_TMO_TARGET_SETTING_BT1886_L_TMO,
PQ_IP_TMO_TARGET_SETTING_DOLBYMETA_L_TMO,
PQ_IP_TMO_TARGET_SETTING_HLG_L_TMO,
PQ_IP_TMO_TARGET_SETTING_NUMS_TMO
} PQ_IP_TMO_TARGET_SETTING_Group_TMO;

extern code U8 MST_SkipRule_IP_TMO[PQ_IP_NUM_TMO];
extern code EN_IPTAB_INFO PQ_IPTAB_INFO_TMO[];
extern code U8 QMAP_Panel_1_TMO[QM_INPUTTYPE_NUM_TMO][PQ_IP_NUM_TMO];

#endif
