
static code char TEXT_IP_TMO_SOURCE_SETTING_TMO[] = "TMO_SOURCE_SETTING";
static code char TEXT_IP_TMO_TARGET_SETTING_TMO[] = "TMO_TARGET_SETTING";


code char* PQ_IP_Text_TMO[] =
{
TEXT_IP_TMO_SOURCE_SETTING_TMO,
TEXT_IP_TMO_TARGET_SETTING_TMO,
};

code char PQ_IPTAB_TMO_SOURCE_SETTING_OFF_Text_TMO[] = "OFF";
code char PQ_IPTAB_TMO_SOURCE_SETTING_RESERVED0_Text_TMO[] = "RESERVED0";
code char PQ_IPTAB_TMO_SOURCE_SETTING_BT709_Text_TMO[] = "BT709";
code char PQ_IPTAB_TMO_SOURCE_SETTING_UNSPECIFIED_Text_TMO[] = "UNSPECIFIED";
code char PQ_IPTAB_TMO_SOURCE_SETTING_RESERVED3_Text_TMO[] = "RESERVED3";
code char PQ_IPTAB_TMO_SOURCE_SETTING_GAMMA2P2_Text_TMO[] = "GAMMA2P2";
code char PQ_IPTAB_TMO_SOURCE_SETTING_GAMMA2P8_Text_TMO[] = "GAMMA2P8";
code char PQ_IPTAB_TMO_SOURCE_SETTING_BT601525_601625_Text_TMO[] = "BT601525_601625";
code char PQ_IPTAB_TMO_SOURCE_SETTING_SMPTE240M_Text_TMO[] = "SMPTE240M";
code char PQ_IPTAB_TMO_SOURCE_SETTING_LINEAR_Text_TMO[] = "LINEAR";
code char PQ_IPTAB_TMO_SOURCE_SETTING_LOG0_Text_TMO[] = "LOG0";
code char PQ_IPTAB_TMO_SOURCE_SETTING_LOG1_Text_TMO[] = "LOG1";
code char PQ_IPTAB_TMO_SOURCE_SETTING_XVYCC_Text_TMO[] = "XVYCC";
code char PQ_IPTAB_TMO_SOURCE_SETTING_BT1361_Text_TMO[] = "BT1361";
code char PQ_IPTAB_TMO_SOURCE_SETTING_SRGB_SYCC_Text_TMO[] = "SRGB_SYCC";
code char PQ_IPTAB_TMO_SOURCE_SETTING_BT2020NCL_Text_TMO[] = "BT2020NCL";
code char PQ_IPTAB_TMO_SOURCE_SETTING_BT2020CL_Text_TMO[] = "BT2020CL";
code char PQ_IPTAB_TMO_SOURCE_SETTING_SMPTE2084_Text_TMO[] = "SMPTE2084";
code char PQ_IPTAB_TMO_SOURCE_SETTING_SMPTE428_Text_TMO[] = "SMPTE428";
code char PQ_IPTAB_TMO_SOURCE_SETTING_ADOBERGB_Text_TMO[] = "ADOBERGB";
code char PQ_IPTAB_TMO_SOURCE_SETTING_BT1886_Text_TMO[] = "BT1886";
code char PQ_IPTAB_TMO_SOURCE_SETTING_DOLBYMETA_Text_TMO[] = "DOLBYMETA";
code char PQ_IPTAB_TMO_SOURCE_SETTING_HLG_Text_TMO[] = "HLG";
code char PQ_IPTAB_TMO_TARGET_SETTING_OFF_Text_TMO[] = "OFF";
code char PQ_IPTAB_TMO_TARGET_SETTING_RESERVED0_H_Text_TMO[] = "RESERVED0_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT709_H_Text_TMO[] = "BT709_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_UNSPECIFIED_H_Text_TMO[] = "UNSPECIFIED_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_RESERVED3_H_Text_TMO[] = "RESERVED3_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P2_H_Text_TMO[] = "GAMMA2P2_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P8_H_Text_TMO[] = "GAMMA2P8_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT601525_601625_H_Text_TMO[] = "BT601525_601625_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE240M_H_Text_TMO[] = "SMPTE240M_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_LINEAR_H_Text_TMO[] = "LINEAR_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_LOG0_H_Text_TMO[] = "LOG0_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_LOG1_H_Text_TMO[] = "LOG1_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_XVYCC_H_Text_TMO[] = "XVYCC_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT1361_H_Text_TMO[] = "BT1361_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_SRGB_SYCC_H_Text_TMO[] = "SRGB_SYCC_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT2020NCL_H_Text_TMO[] = "BT2020NCL_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT2020CL_H_Text_TMO[] = "BT2020CL_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE2084_H_Text_TMO[] = "SMPTE2084_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE428_H_Text_TMO[] = "SMPTE428_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_ADOBERGB_H_Text_TMO[] = "ADOBERGB_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT1886_H_Text_TMO[] = "BT1886_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_DOLBYMETA_H_Text_TMO[] = "DOLBYMETA_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_HLG_H_Text_TMO[] = "HLG_H";
code char PQ_IPTAB_TMO_TARGET_SETTING_RESERVED0_M_Text_TMO[] = "RESERVED0_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT709_M_Text_TMO[] = "BT709_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_UNSPECIFIED_M_Text_TMO[] = "UNSPECIFIED_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_RESERVED3_M_Text_TMO[] = "RESERVED3_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P2_M_Text_TMO[] = "GAMMA2P2_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P8_M_Text_TMO[] = "GAMMA2P8_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT601525_601625_M_Text_TMO[] = "BT601525_601625_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE240M_M_Text_TMO[] = "SMPTE240M_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_LINEAR_M_Text_TMO[] = "LINEAR_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_LOG0_M_Text_TMO[] = "LOG0_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_LOG1_M_Text_TMO[] = "LOG1_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_XVYCC_M_Text_TMO[] = "XVYCC_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT1361_M_Text_TMO[] = "BT1361_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_SRGB_SYCC_M_Text_TMO[] = "SRGB_SYCC_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT2020NCL_M_Text_TMO[] = "BT2020NCL_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT2020CL_M_Text_TMO[] = "BT2020CL_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE2084_M_Text_TMO[] = "SMPTE2084_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE428_M_Text_TMO[] = "SMPTE428_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_ADOBERGB_M_Text_TMO[] = "ADOBERGB_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT1886_M_Text_TMO[] = "BT1886_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_DOLBYMETA_M_Text_TMO[] = "DOLBYMETA_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_HLG_M_Text_TMO[] = "HLG_M";
code char PQ_IPTAB_TMO_TARGET_SETTING_RESERVED0_L_Text_TMO[] = "RESERVED0_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT709_L_Text_TMO[] = "BT709_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_UNSPECIFIED_L_Text_TMO[] = "UNSPECIFIED_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_RESERVED3_L_Text_TMO[] = "RESERVED3_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P2_L_Text_TMO[] = "GAMMA2P2_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P8_L_Text_TMO[] = "GAMMA2P8_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT601525_601625_L_Text_TMO[] = "BT601525_601625_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE240M_L_Text_TMO[] = "SMPTE240M_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_LINEAR_L_Text_TMO[] = "LINEAR_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_LOG0_L_Text_TMO[] = "LOG0_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_LOG1_L_Text_TMO[] = "LOG1_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_XVYCC_L_Text_TMO[] = "XVYCC_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT1361_L_Text_TMO[] = "BT1361_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_SRGB_SYCC_L_Text_TMO[] = "SRGB_SYCC_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT2020NCL_L_Text_TMO[] = "BT2020NCL_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT2020CL_L_Text_TMO[] = "BT2020CL_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE2084_L_Text_TMO[] = "SMPTE2084_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_SMPTE428_L_Text_TMO[] = "SMPTE428_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_ADOBERGB_L_Text_TMO[] = "ADOBERGB_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_BT1886_L_Text_TMO[] = "BT1886_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_DOLBYMETA_L_Text_TMO[] = "DOLBYMETA_L";
code char PQ_IPTAB_TMO_TARGET_SETTING_HLG_L_Text_TMO[] = "HLG_L";

code char* PQ_IP_TMO_SOURCE_SETTING_Text_TMO[] =
{
PQ_IPTAB_TMO_SOURCE_SETTING_OFF_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_RESERVED0_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_BT709_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_UNSPECIFIED_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_RESERVED3_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_GAMMA2P2_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_GAMMA2P8_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_BT601525_601625_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_SMPTE240M_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_LINEAR_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_LOG0_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_LOG1_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_XVYCC_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_BT1361_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_SRGB_SYCC_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_BT2020NCL_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_BT2020CL_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_SMPTE2084_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_SMPTE428_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_ADOBERGB_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_BT1886_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_DOLBYMETA_Text_TMO,
PQ_IPTAB_TMO_SOURCE_SETTING_HLG_Text_TMO,
};

code char* PQ_IP_TMO_TARGET_SETTING_Text_TMO[] =
{
PQ_IPTAB_TMO_TARGET_SETTING_OFF_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_RESERVED0_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT709_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_UNSPECIFIED_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_RESERVED3_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P2_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P8_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT601525_601625_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE240M_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_LINEAR_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_LOG0_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_LOG1_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_XVYCC_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT1361_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_SRGB_SYCC_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT2020NCL_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT2020CL_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE2084_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE428_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_ADOBERGB_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT1886_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_DOLBYMETA_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_HLG_H_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_RESERVED0_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT709_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_UNSPECIFIED_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_RESERVED3_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P2_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P8_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT601525_601625_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE240M_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_LINEAR_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_LOG0_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_LOG1_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_XVYCC_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT1361_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_SRGB_SYCC_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT2020NCL_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT2020CL_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE2084_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE428_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_ADOBERGB_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT1886_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_DOLBYMETA_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_HLG_M_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_RESERVED0_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT709_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_UNSPECIFIED_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_RESERVED3_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P2_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_GAMMA2P8_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT601525_601625_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE240M_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_LINEAR_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_LOG0_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_LOG1_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_XVYCC_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT1361_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_SRGB_SYCC_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT2020NCL_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT2020CL_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE2084_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_SMPTE428_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_ADOBERGB_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_BT1886_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_DOLBYMETA_L_Text_TMO,
PQ_IPTAB_TMO_TARGET_SETTING_HLG_L_Text_TMO,
};

code char** PQ_IPTAB_TEXT_TMO[]=
{
PQ_IP_TMO_SOURCE_SETTING_Text_TMO,
PQ_IP_TMO_TARGET_SETTING_Text_TMO,
};

