
obj-$(CONFIG_AMAZON_KLOG_CONSOLE)	+= klog_console.o
obj-$(CONFIG_AMAZON_SIGN_OF_LIFE) += sign_of_life.o
obj-$(CONFIG_AMAZON_SIGN_OF_LIFE_MSTAR) += sign_of_life_mstar.o
obj-$(CONFIG_AMAZON_PLATFORM_BT_RFKILL)	+= platform_bt_rfkill.o

obj-$(CONFIG_AMAZON_METRICS_LOG)	+= amazon_logger.o
obj-$(CONFIG_AMAZON_METRICS_LOG_TEST)	+= amazon_logger_test.o
obj-$(CONFIG_AMAZON_SILENT_OTA_BACKLIGHT) += silent_ota_backlight_mstar.o
