/*
 * (C) Copyright 2000-2006
 * Wolfgang Denk, DENX Software Engineering, wd@denx.de.
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

#ifndef	__VERSION_H__
#define	__VERSION_H__

#ifndef DO_DEPS_ONLY
#include "version_autogenerated.h"
#endif
#define MBOOT_CL  "MBOT-1106.0.10.361e1463143bdb31ea001f5f2b3a9531d0db625e\n"
#define MSTARCORECOMMIT "a07dccf96057c43908e67c814ac9892706b6b913"
#define MSTARAPPCOMMIT "a07dccf96057c43908e67c814ac9892706b6b913"
#define MSTARCUSTOMERCOMMIT "a07dccf96057c43908e67c814ac9892706b6b913"
#define TOOLCOMMIT "2ef70f3f107ebf889fe3e88016aa2de1001ad288"
#define UBOOTCOMMIT "a07dccf96057c43908e67c814ac9892706b6b913"
#define SBOOTCOMMIT "1b37f249cec3149e5a2081bb38331e4946d2361c"

#endif	/* __VERSION_H__ */
